language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check
addons:
  apt:
    packages:
      - oracle-java8-installer
deploy:
  provider: releases
  api_key: GHToken
  file: "build/distributions/jnutrition.zip"
  skip_cleanup: true
  on:
    tags: true